env:
  node: true
  es2022: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  no-unused-vars: off
overrides:
  - files: [ "**/*.test.js" ]
    env:
      mocha: true
